### ISSUE TITLE
Playground Radix - Web Console link directs to prod Radix

### ISSUE THREAD

**Issue by fcestari** [equinor/radix-public-site#209]
Not sure if this is the correct repo to post this issue, but I noticed that the `Web Console` link (menu bar) of the Playground Radix page points to `https://console.radix.equinor.com/` instead of `https://console.playground.radix.equinor.com/`.

**Comment by emirgens** [comment]
This is as per design. There are only one version of the Radix documentation (public site), the links on top actually points to the main console, which also have the Playground "tab".
